### ISSUE TITLE
run rc-ycsb.sh class not found exception

### ISSUE THREAD

**Issue by woonhak** [PlatformLab/ramcloud-ycsb#4]
I tried to run ramcloud ycsb,
I have a single cluster setup which is running both coordinator and server.
I've modified runYcsb and other scripts to cope with my cluster environment,
so I can initiate coordinate and server successfully.

However, I've got following errors to start clients:

java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)                                               
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RamCloudClient
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
Exception in thread "Thread-1" java.lang.NullPointerException
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)
Exception in thread "Thread-2" Exception in thread "Thread-3" java.lang.NullPointerException
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)
java.lang.NullPointerException
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)
Exception in thread "Thread-5" java.lang.NullPointerException

**Comment by woonhak** [comment]
I added missing classpath for RamCloudClient.class in rc-ycsb.sh, now it works fine.
(or just put RamCloudClient.class to YCSB/ramcloud/src/main/java/com/yahoo/ycsb/db/)
